# Configuration for Pull Request Labeler
# https://github.com/actions/labeler

# Python code changes
'python':
  - '**/*.py'

# Configuration changes
'configuration':
  - 'config.py'
  - '.env.example'
  - '*.yml'
  - '*.yaml'

# Documentation
'documentation':
  - '**/*.md'
  - 'docs/**/*'

# Tests
'tests':
  - 'tests/**/*'
  - 'test_*.py'
  - '**/test_*.py'

# CI/CD
'ci/cd':
  - '.github/workflows/**/*'
  - '.github/**/*.yml'
  - 'Dockerfile'
  - 'docker-compose.yml'
  - '.dockerignore'

# Frontend/HTML
'frontend':
  - '**/*.html'
  - '**/*.css'
  - '**/*.js'

# Memory/Database
'memory':
  - 'src/memory/**/*'
  - 'src/models/memory_models.py'
  - 'src/services/memory_service.py'
  - 'database/**/*'

# Causal Memory
'causal-memory':
  - 'src/utils/causal_memory_core.py'

# Proxy Server
'proxy-server':
  - 'proxy_server.py'

# Dependencies
'dependencies':
  - 'requirements.txt'
  - 'setup.py'
  - 'pyproject.toml'

# Stage 2
'stage-2':
  - 'src/memory/**/*'
  - 'src/models/memory_models.py'
  - 'src/services/memory_service.py'

# Stage 3
'stage-3':
  - 'crucible.py'
  - 'src/utils/causal_memory_core.py'
